services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8073:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: adisalafudin
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress_db
    depends_on:
      - db
      - phpmyadmin
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: adisalafudin
      MYSQL_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_wordpress
    restart: always
    ports:
      - 8180:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
volumes:
  wordpress:
  db:
